# Generated by Django 3.0 on 2019-12-16 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191216_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='comment',
        ),
    ]
