# Generated by Django 3.0 on 2019-12-18 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_favorite_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='is_favorite',
        ),
    ]
