# Generated by Django 3.0 on 2019-12-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_favorite_is_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
