# Generated by Django 3.0 on 2019-12-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comment'),
        ('account', '0008_delete_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite',
            field=models.ManyToManyField(related_name='favorited_by', to='blog.Post'),
        ),
    ]
