# Generated by Django 3.0 on 2019-12-19 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20191218_1618'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
