# Generated by Django 3.0 on 2019-12-16 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_subcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcomment',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='subcomments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.SubComment'),
        ),
    ]
