# Generated by Django 3.0 on 2019-12-16 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191216_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='subcomments',
        ),
        migrations.DeleteModel(
            name='SubComment',
        ),
    ]
