# Generated by Django 3.0 on 2019-12-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
