# Generated by Django 3.0 on 2019-12-17 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_favorite_is_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
